// 程序内使用的结构，方便缓存到 Redis 等工具内（毕竟比 JSON 省内存）

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v5.26.1
// source: binary.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Vec2D struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X uint64 `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y uint64 `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
}

func (x *Vec2D) Reset() {
	*x = Vec2D{}
	if protoimpl.UnsafeEnabled {
		mi := &file_binary_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Vec2D) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vec2D) ProtoMessage() {}

func (x *Vec2D) ProtoReflect() protoreflect.Message {
	mi := &file_binary_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vec2D.ProtoReflect.Descriptor instead.
func (*Vec2D) Descriptor() ([]byte, []int) {
	return file_binary_proto_rawDescGZIP(), []int{0}
}

func (x *Vec2D) GetX() uint64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Vec2D) GetY() uint64 {
	if x != nil {
		return x.Y
	}
	return 0
}

type NowDungeon struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Rooms        []*Room `protobuf:"bytes,1,rep,name=rooms,proto3" json:"rooms,omitempty"`
	PlayerId     uint64  `protobuf:"varint,2,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	NowRoomId    uint64  `protobuf:"varint,3,opt,name=now_room_id,json=nowRoomId,proto3" json:"now_room_id,omitempty"`
	NowMonsterId uint64  `protobuf:"varint,4,opt,name=now_monster_id,json=nowMonsterId,proto3" json:"now_monster_id,omitempty"`
}

func (x *NowDungeon) Reset() {
	*x = NowDungeon{}
	if protoimpl.UnsafeEnabled {
		mi := &file_binary_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NowDungeon) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NowDungeon) ProtoMessage() {}

func (x *NowDungeon) ProtoReflect() protoreflect.Message {
	mi := &file_binary_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NowDungeon.ProtoReflect.Descriptor instead.
func (*NowDungeon) Descriptor() ([]byte, []int) {
	return file_binary_proto_rawDescGZIP(), []int{1}
}

func (x *NowDungeon) GetRooms() []*Room {
	if x != nil {
		return x.Rooms
	}
	return nil
}

func (x *NowDungeon) GetPlayerId() uint64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *NowDungeon) GetNowRoomId() uint64 {
	if x != nil {
		return x.NowRoomId
	}
	return 0
}

func (x *NowDungeon) GetNowMonsterId() uint64 {
	if x != nil {
		return x.NowMonsterId
	}
	return 0
}

type Room struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        uint64     `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"` // 房间、走廊等实体连续 ID
	Pos       *Vec2D     `protobuf:"bytes,2,opt,name=pos,proto3" json:"pos,omitempty"`
	Title     string     `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Box       []*Box     `protobuf:"bytes,4,rep,name=box,proto3" json:"box,omitempty"`
	LinkRooms []uint64   `protobuf:"varint,5,rep,packed,name=link_rooms,json=linkRooms,proto3" json:"link_rooms,omitempty"` // 相连的走廊
	Monsters  []*Monster `protobuf:"bytes,6,rep,name=monsters,proto3" json:"monsters,omitempty"`
}

func (x *Room) Reset() {
	*x = Room{}
	if protoimpl.UnsafeEnabled {
		mi := &file_binary_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Room) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Room) ProtoMessage() {}

func (x *Room) ProtoReflect() protoreflect.Message {
	mi := &file_binary_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Room.ProtoReflect.Descriptor instead.
func (*Room) Descriptor() ([]byte, []int) {
	return file_binary_proto_rawDescGZIP(), []int{2}
}

func (x *Room) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Room) GetPos() *Vec2D {
	if x != nil {
		return x.Pos
	}
	return nil
}

func (x *Room) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Room) GetBox() []*Box {
	if x != nil {
		return x.Box
	}
	return nil
}

func (x *Room) GetLinkRooms() []uint64 {
	if x != nil {
		return x.LinkRooms
	}
	return nil
}

func (x *Room) GetMonsters() []*Monster {
	if x != nil {
		return x.Monsters
	}
	return nil
}

type Monster struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           uint64      `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	GoodsHasList []*GoodsHas `protobuf:"bytes,2,rep,name=goodsHasList,proto3" json:"goodsHasList,omitempty"`
	HpBase       uint64      `protobuf:"varint,3,opt,name=hp_base,json=hpBase,proto3" json:"hp_base,omitempty"`
	AttackBase   uint64      `protobuf:"varint,4,opt,name=attack_base,json=attackBase,proto3" json:"attack_base,omitempty"`
	DefenceBase  uint64      `protobuf:"varint,5,opt,name=defence_base,json=defenceBase,proto3" json:"defence_base,omitempty"`
}

func (x *Monster) Reset() {
	*x = Monster{}
	if protoimpl.UnsafeEnabled {
		mi := &file_binary_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Monster) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Monster) ProtoMessage() {}

func (x *Monster) ProtoReflect() protoreflect.Message {
	mi := &file_binary_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Monster.ProtoReflect.Descriptor instead.
func (*Monster) Descriptor() ([]byte, []int) {
	return file_binary_proto_rawDescGZIP(), []int{3}
}

func (x *Monster) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Monster) GetGoodsHasList() []*GoodsHas {
	if x != nil {
		return x.GoodsHasList
	}
	return nil
}

func (x *Monster) GetHpBase() uint64 {
	if x != nil {
		return x.HpBase
	}
	return 0
}

func (x *Monster) GetAttackBase() uint64 {
	if x != nil {
		return x.AttackBase
	}
	return 0
}

func (x *Monster) GetDefenceBase() uint64 {
	if x != nil {
		return x.DefenceBase
	}
	return 0
}

// 容器
type Box struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Searched     bool        `protobuf:"varint,1,opt,name=searched,proto3" json:"searched,omitempty"`
	GoodsHasList []*GoodsHas `protobuf:"bytes,2,rep,name=goodsHasList,proto3" json:"goodsHasList,omitempty"`
}

func (x *Box) Reset() {
	*x = Box{}
	if protoimpl.UnsafeEnabled {
		mi := &file_binary_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Box) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Box) ProtoMessage() {}

func (x *Box) ProtoReflect() protoreflect.Message {
	mi := &file_binary_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Box.ProtoReflect.Descriptor instead.
func (*Box) Descriptor() ([]byte, []int) {
	return file_binary_proto_rawDescGZIP(), []int{4}
}

func (x *Box) GetSearched() bool {
	if x != nil {
		return x.Searched
	}
	return false
}

func (x *Box) GetGoodsHasList() []*GoodsHas {
	if x != nil {
		return x.GoodsHasList
	}
	return nil
}

type GoodsHas struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Index uint64 `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Count uint32 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *GoodsHas) Reset() {
	*x = GoodsHas{}
	if protoimpl.UnsafeEnabled {
		mi := &file_binary_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GoodsHas) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoodsHas) ProtoMessage() {}

func (x *GoodsHas) ProtoReflect() protoreflect.Message {
	mi := &file_binary_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoodsHas.ProtoReflect.Descriptor instead.
func (*GoodsHas) Descriptor() ([]byte, []int) {
	return file_binary_proto_rawDescGZIP(), []int{5}
}

func (x *GoodsHas) GetIndex() uint64 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *GoodsHas) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

var File_binary_proto protoreflect.FileDescriptor

var file_binary_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x62, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09,
	0x74, 0x65, 0x78, 0x74, 0x5f, 0x6c, 0x69, 0x66, 0x65, 0x22, 0x23, 0x0a, 0x05, 0x56, 0x65, 0x63,
	0x32, 0x44, 0x12, 0x0c, 0x0a, 0x01, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x01, 0x78,
	0x12, 0x0c, 0x0a, 0x01, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x01, 0x79, 0x22, 0x96,
	0x01, 0x0a, 0x0a, 0x4e, 0x6f, 0x77, 0x44, 0x75, 0x6e, 0x67, 0x65, 0x6f, 0x6e, 0x12, 0x25, 0x0a,
	0x05, 0x72, 0x6f, 0x6f, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x74,
	0x65, 0x78, 0x74, 0x5f, 0x6c, 0x69, 0x66, 0x65, 0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x05, 0x72,
	0x6f, 0x6f, 0x6d, 0x73, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x5f, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49,
	0x64, 0x12, 0x1e, 0x0a, 0x0b, 0x6e, 0x6f, 0x77, 0x5f, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x69, 0x64,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x6e, 0x6f, 0x77, 0x52, 0x6f, 0x6f, 0x6d, 0x49,
	0x64, 0x12, 0x24, 0x0a, 0x0e, 0x6e, 0x6f, 0x77, 0x5f, 0x6d, 0x6f, 0x6e, 0x73, 0x74, 0x65, 0x72,
	0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0c, 0x6e, 0x6f, 0x77, 0x4d, 0x6f,
	0x6e, 0x73, 0x74, 0x65, 0x72, 0x49, 0x64, 0x22, 0xc1, 0x01, 0x0a, 0x04, 0x52, 0x6f, 0x6f, 0x6d,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x22, 0x0a, 0x03, 0x70, 0x6f, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e,
	0x74, 0x65, 0x78, 0x74, 0x5f, 0x6c, 0x69, 0x66, 0x65, 0x2e, 0x56, 0x65, 0x63, 0x32, 0x44, 0x52,
	0x03, 0x70, 0x6f, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x20, 0x0a, 0x03, 0x62, 0x6f,
	0x78, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x74, 0x65, 0x78, 0x74, 0x5f, 0x6c,
	0x69, 0x66, 0x65, 0x2e, 0x42, 0x6f, 0x78, 0x52, 0x03, 0x62, 0x6f, 0x78, 0x12, 0x1d, 0x0a, 0x0a,
	0x6c, 0x69, 0x6e, 0x6b, 0x5f, 0x72, 0x6f, 0x6f, 0x6d, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x04,
	0x52, 0x09, 0x6c, 0x69, 0x6e, 0x6b, 0x52, 0x6f, 0x6f, 0x6d, 0x73, 0x12, 0x2e, 0x0a, 0x08, 0x6d,
	0x6f, 0x6e, 0x73, 0x74, 0x65, 0x72, 0x73, 0x18, 0x06, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e,
	0x74, 0x65, 0x78, 0x74, 0x5f, 0x6c, 0x69, 0x66, 0x65, 0x2e, 0x4d, 0x6f, 0x6e, 0x73, 0x74, 0x65,
	0x72, 0x52, 0x08, 0x6d, 0x6f, 0x6e, 0x73, 0x74, 0x65, 0x72, 0x73, 0x22, 0xaf, 0x01, 0x0a, 0x07,
	0x4d, 0x6f, 0x6e, 0x73, 0x74, 0x65, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x37, 0x0a, 0x0c, 0x67, 0x6f, 0x6f, 0x64, 0x73,
	0x48, 0x61, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e,
	0x74, 0x65, 0x78, 0x74, 0x5f, 0x6c, 0x69, 0x66, 0x65, 0x2e, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x48,
	0x61, 0x73, 0x52, 0x0c, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x48, 0x61, 0x73, 0x4c, 0x69, 0x73, 0x74,
	0x12, 0x17, 0x0a, 0x07, 0x68, 0x70, 0x5f, 0x62, 0x61, 0x73, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x06, 0x68, 0x70, 0x42, 0x61, 0x73, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x61, 0x74, 0x74,
	0x61, 0x63, 0x6b, 0x5f, 0x62, 0x61, 0x73, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0a,
	0x61, 0x74, 0x74, 0x61, 0x63, 0x6b, 0x42, 0x61, 0x73, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x64, 0x65,
	0x66, 0x65, 0x6e, 0x63, 0x65, 0x5f, 0x62, 0x61, 0x73, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x0b, 0x64, 0x65, 0x66, 0x65, 0x6e, 0x63, 0x65, 0x42, 0x61, 0x73, 0x65, 0x22, 0x5a, 0x0a,
	0x03, 0x42, 0x6f, 0x78, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x65, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x65, 0x64,
	0x12, 0x37, 0x0a, 0x0c, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x48, 0x61, 0x73, 0x4c, 0x69, 0x73, 0x74,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x74, 0x65, 0x78, 0x74, 0x5f, 0x6c, 0x69,
	0x66, 0x65, 0x2e, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x48, 0x61, 0x73, 0x52, 0x0c, 0x67, 0x6f, 0x6f,
	0x64, 0x73, 0x48, 0x61, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x36, 0x0a, 0x08, 0x47, 0x6f, 0x6f,
	0x64, 0x73, 0x48, 0x61, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x14, 0x0a, 0x05, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x42, 0x0c, 0x5a, 0x0a, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x73, 0x2f, 0x70, 0x62, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_binary_proto_rawDescOnce sync.Once
	file_binary_proto_rawDescData = file_binary_proto_rawDesc
)

func file_binary_proto_rawDescGZIP() []byte {
	file_binary_proto_rawDescOnce.Do(func() {
		file_binary_proto_rawDescData = protoimpl.X.CompressGZIP(file_binary_proto_rawDescData)
	})
	return file_binary_proto_rawDescData
}

var file_binary_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_binary_proto_goTypes = []interface{}{
	(*Vec2D)(nil),      // 0: text_life.Vec2D
	(*NowDungeon)(nil), // 1: text_life.NowDungeon
	(*Room)(nil),       // 2: text_life.Room
	(*Monster)(nil),    // 3: text_life.Monster
	(*Box)(nil),        // 4: text_life.Box
	(*GoodsHas)(nil),   // 5: text_life.GoodsHas
}
var file_binary_proto_depIdxs = []int32{
	2, // 0: text_life.NowDungeon.rooms:type_name -> text_life.Room
	0, // 1: text_life.Room.pos:type_name -> text_life.Vec2D
	4, // 2: text_life.Room.box:type_name -> text_life.Box
	3, // 3: text_life.Room.monsters:type_name -> text_life.Monster
	5, // 4: text_life.Monster.goodsHasList:type_name -> text_life.GoodsHas
	5, // 5: text_life.Box.goodsHasList:type_name -> text_life.GoodsHas
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_binary_proto_init() }
func file_binary_proto_init() {
	if File_binary_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_binary_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Vec2D); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_binary_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NowDungeon); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_binary_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Room); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_binary_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Monster); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_binary_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Box); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_binary_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GoodsHas); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_binary_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_binary_proto_goTypes,
		DependencyIndexes: file_binary_proto_depIdxs,
		MessageInfos:      file_binary_proto_msgTypes,
	}.Build()
	File_binary_proto = out.File
	file_binary_proto_rawDesc = nil
	file_binary_proto_goTypes = nil
	file_binary_proto_depIdxs = nil
}
